# Generated by Django 4.2.2 on 2023-09-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='apellido',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='email',
        ),
        migrations.AddField(
            model_name='productos',
            name='sku',
            field=models.IntegerField(default=1),
        ),
    ]
